---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-assessment-deployment
  labels:
    app: code-assessment-deployment
spec:
  selector:
    matchLabels:
      app: code-assessment-deployment
  template:
    metadata:
      labels:
        app: code-assessment-deployment
    spec:
      containers:
        - name: code-assessment-service
          image: com.backend.programming.learning.system/code.assessment.service:1.0-SNAPSHOT
          env:
            - name: LOGGING_LEVEL_COM_BACKEND_PROGRAMMING_LEARNING_SYSTEM
              value: "info"
            - name: LOGGING_LEVEL_ROOT
              value: "info"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://host.docker.internal:5432/code-assessment-service?currentSchema=public&binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "localdb"
            - name: KAFKA-CONFIG_BOOTSTRAP-SERVERS
              value: "local-confluent-kafka-cp-kafka-headless:9092"
            - name: SPRING_ZIPKIN_SENDER_TYPE
              value: "kafka"
            - name: SPRING_KAFKA_BOOTSTRAP-SERVERS
              value: "local-confluent-kafka-cp-kafka-headless:9092"
            - name: SPRING_SLEUTH_SAMPLER_PROBABILITY
              value: "1.0"
            - name: KAFKA-CONFIG_SCHEMA-REGISTRY-URL
              value: "http://local-confluent-kafka-cp-schema-registry:8081"
            - name: SPRING_CLOUD_CONFIG_URI
              value: "http://config-server:9999"
            - name: EUREKA_CLIENT_SERVICE-URL_DEFAULT-ZONE
              value: "http://discovery-service-1:8761/eureka/"
          resources:
            limits:
              cpu: "500m"
              memory: "800Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
          volumeMounts:
            - name: code-assessment-service-log
              mountPath: /logs
      volumes:
        - name: code-assessment-service-log
          persistentVolumeClaim:
            claimName: code-assessment-service-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: code-assessment-service
  namespace: default
  labels:
    app: code-assessment-service
spec:
  selector:
    app: code-assessment-deployment
  ports:
    - name: code-assessment-service-port
      protocol: TCP
      port: 8183
  type: LoadBalancer
  loadBalancerIP: ""