---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server-deployment
  namespace: default
  labels:
    app: config-server-deployment
spec:
  selector:
    matchLabels:
      app: config-server-deployment
  template:
    metadata:
      labels:
        app: config-server-deployment
    spec:
      containers:
        - name: config-server-service
          image: com.backend.programming.learning.system/config.server:1.0-SNAPSHOT
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-Xmx256m -Xms128m"
            - name: LOG_APP-NAME
              value: "config-server"
            - name: SERVER_PORT
              value: "9999"
          resources:
            limits:
              cpu: "500m"
              memory: "1Gi"
            requests:
              cpu: "200m"
              memory: "256Mi"
          volumeMounts:
            - mountPath: /config-server/logs
              name: config-server-log
      volumes:
        - name: config-server-log
          persistentVolumeClaim:
            claimName: config-server-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: config-server
  namespace: default
  labels:
    app: config-server
spec:
  selector:
    app: config-server-deployment
  ports:
    - name: config-server-service-port
      protocol: TCP
      port: 9999
  type: LoadBalancer
  loadBalancerIP: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-server-pvc
  namespace: default
  labels:
    app: config-server-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
