---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server-deployment
  namespace: default
  labels:
    app: config-server-deployment
spec:
  selector:
    matchLabels:
      app: config-server-deployment
  template:
    metadata:
      labels:
        app: config-server-deployment
    spec:
      containers:
        - name: config-server-service
          image: com.backend.programming.learning.system/config.server:1.0-SNAPSHOT
          env:
            - name: LOG_APP-NAME
              value: "config-server"
          resources:
            limits:
              cpu: "500m"
              memory: "1024Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
          volumeMounts:
            - mountPath: /workspace/config-server/logs
              name: config-server-claim0
      volumes:
        - name: config-server-claim0
          persistentVolumeClaim:
            claimName: config-server-claim0
---
apiVersion: v1
kind: Service
metadata:
  name: config-server-service
  namespace: default
  labels:
    app: config-server-service
spec:
  selector:
    app: config-server-deployment
  ports:
    - name: config-server-service-port
      protocol: TCP
      port: 9999
  type: LoadBalancer
  loadBalancerIP: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-server-claim0
  namespace: default
  labels:
    app: config-server-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
