---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-deployment
  namespace: default
  labels:
    app: core-deployment
spec:
  selector:
    matchLabels:
      app: core-deployment
  template:
    metadata:
      labels:
        app: core-deployment
    spec:
      containers:
        - name: core-service
          image: com.backend.programming.learning.system/core.service:1.0-SNAPSHOT
          env:
            - name: LOGGING_LEVEL_COM_BACKEND_PROGRAMMING_LEARNING_SYSTEM
              value: "info"
            - name: LOGGING_LEVEL_ROOT
              value: "info"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://host.docker.internal:5432/core-service?currentSchema=public&binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "localdb"
            - name: KAFKA-CONFIG_BOOTSTRAP-SERVERS
              value: "local-confluent-kafka-cp-kafka-headless:9092"
            - name: SPRING_KAFKA_BOOTSTRAP-SERVERS
              value: "local-confluent-kafka-cp-kafka-headless:9092"
            - name: KAFKA-CONFIG_SCHEMA-REGISTRY-URL
              value: "http://local-confluent-kafka-cp-schema-registry:8081"
            - name: SPRING_CLOUD_CONFIG_URI
              value: "http://config-server:9999"
            - name: EUREKA_CLIENT_SERVICE-URL_DEFAULT-ZONE
              value: "http://discovery-service-1:8761/eureka/,http://discovery-service-2:8762/eureka/"
          volumeMounts:
            - name: core-service-log
              mountPath: /workspace/core-service/logs
          resources:
            limits:
              cpu: "500m"
              memory: "1024Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
      volumes:
        - name: core-service-log
          persistentVolumeClaim:
            claimName: core-service-claim0
---
apiVersion: v1
kind: Service
metadata:
  name: core-service
  namespace: default
  labels:
    app: core-service
spec:
  selector:
    app: core-deployment
  ports:
    - name: core-service-port
      protocol: TCP
      port: 8181
  type: LoadBalancer
  loadBalancerIP: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: core-service-claim0
  namespace: default
  labels:
    app: core-service-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
