---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-deployment
  namespace: default
  labels:
    app: course-deployment
spec:
  selector:
    matchLabels:
      app: course-deployment
  template:
    metadata:
      labels:
        app: course-deployment
    spec:
      containers:
        - name: course-service
          image: com.backend.programming.learning.system/course.service:1.0-SNAPSHOT
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: LOGGING_LEVEL_COM_BACKEND_PROGRAMMING_LEARNING_SYSTEM
              value: "info"
            - name: LOGGING_LEVEL_ROOT
              value: "info"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://host.docker.internal:5432/course-service?currentSchema=public&binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "localdb"
            - name: KAFKA-CONFIG_BOOTSTRAP-SERVERS
              value: "local-confluent-kafka-cp-kafka-headless:9092"
            - name: SPRING_ZIPKIN_BASE_URL
              value: "http://zipkin:9411"
            - name: SPRING_ZIPKIN_SENDER_TYPE
              value: "kafka"
            - name: SPRING_KAFKA_BOOTSTRAP-SERVERS
              value: "local-confluent-kafka-cp-kafka-headless:9092"
            - name: SPRING_SLEUTH_SAMPLER_PROBABILITY
              value: "1.0"
            - name: KAFKA-CONFIG_SCHEMA-REGISTRY-URL
              value: "http://local-confluent-kafka-cp-schema-registry:8081"
            - name: CONFIG_SERVER
              value: "http://config-server:9999"
            - name: EUREKA_SERVER
              value: "http://discovery-service-1:8761/eureka"
          volumeMounts:
            - name: course-service-log
              mountPath: /logs
          resources:
            limits:
              cpu: "500m"
              memory: "1Gi"
            requests:
              cpu: "200m"
              memory: "256Mi"
      volumes:
        - name: course-service-log
          persistentVolumeClaim:
            claimName: course-service-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: course-service
  namespace: default
  labels:
    app: course-service
spec:
  selector:
    app: course-deployment
  ports:
    - name: course-service-port
      protocol: TCP
      port: 8184
    - name: socket-service-port
      protocol: TCP
      port: 8085
  type: LoadBalancer
  loadBalancerIP: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: course-service-pvc
  namespace: default
  labels:
    app: course-service-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi