---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin-mysql-deployment
  namespace: default
  labels:
    app: zipkin-mysql-deployment
spec:
  selector:
    matchLabels:
      app: zipkin-mysql-deployment
  template:
    metadata:
      labels:
        app: zipkin-mysql-deployment
    spec:
      containers:
        - name: zipkin-mysql
          image: openzipkin/zipkin-mysql:2.22.2
          env:
            - name: MYSQL_USER
              value: "zipkin"
            - name: MYSQL_PASSWORD
              value: "zipkin"
            - name: MYSQL_DATABASE
              value: "zipkin"
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: default
  labels:
    app: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: zipkin-mysql-service
  namespace: default
  labels:
    app: zipkin-mysql-deployment
spec:
  selector:
    app: zipkin-mysql-deployment
  ports:
    - name: zipkin-mysql-service-port
      protocol: TCP
      port: 3306
  type: LoadBalancer