---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  namespace: default
  labels:
    app: auth-deployment
spec:
  selector:
    matchLabels:
      app: auth-deployment
  template:
    metadata:
      labels:
        app: auth-deployment
    spec:
      containers:
        - name: auth-service
          image: asia-southeast1-docker.pkg.dev/programming-learning-system/backend-programming-learning-system-repository/auth.service:1.0-SNAPSHOT
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://aws-postgresql.ctso2e4midpm.ap-southeast-2.rds.amazonaws.com:5432/auth-service?currentSchema=order&binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "postgresadmin"
            - name: SPRING_DATASOURCE_INITIALIZATION-MODE
              value: "never"
            - name: KAFKA-CONFIG_BOOTSTRAP-SERVERS
              value: "gke-confluent-kafka-cp-kafka-headless:9092"
            - name: KAFKA-CONFIG_SCHEMA-REGISTRY-URL
              value: "http://gke-confluent-kafka-cp-schema-registry:8081"
          resources:
            limits:
              cpu: "500m"
              memory: "1024Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: default
  labels:
    app: auth-service
spec:
  selector:
    app: auth-deployment
  ports:
    - name: auth-service-port
      protocol: TCP
      port: 8182
  type: LoadBalancer
  loadBalancerIP: ""
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: auth-deployment-hpa
  namespace: default
  labels:
    app: auth-deployment
spec:
  scaleTargetRef:
    kind: Deployment
    name: auth-deployment
    apiVersion: apps/v1
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 85
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-deployment
  namespace: default
  labels:
    app: core-deployment
spec:
  selector:
    matchLabels:
      app: core-deployment
  template:
    metadata:
      labels:
        app: core-deployment
    spec:
      containers:
        - name: core-service
          image: asia-southeast1-docker.pkg.dev/programming-learning-system/backend-programming-learning-system-repository/core.service:1.0-SNAPSHOT
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://aws-postgresql.ctso2e4midpm.ap-southeast-2.rds.amazonaws.com:5432/core-service?currentSchema=public&binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "postgresadmin"
            - name: SPRING_DATASOURCE_INITIALIZATION-MODE
              value: "never"
            - name: KAFKA-CONFIG_BOOTSTRAP-SERVERS
              value: "gke-confluent-kafka-cp-kafka-headless:9092"
            - name: KAFKA-CONFIG_SCHEMA-REGISTRY-URL
              value: "http://gke-confluent-kafka-cp-schema-registry:8081"
          resources:
            limits:
              cpu: "500m"
              memory: "1024Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: core-service
  namespace: default
  labels:
    app: core-service
spec:
  selector:
    app: core-deployment
  ports:
    - name: core-service-port
      protocol: TCP
      port: 8181
  type: LoadBalancer
  loadBalancerIP: ""
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: core-deployment-hpa
  namespace: default
  labels:
    app: core-deployment
spec:
  scaleTargetRef:
    kind: Deployment
    name: core-deployment
    apiVersion: apps/v1
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 85
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-deployment
  namespace: default
  labels:
    app: course-deployment
spec:
  selector:
    matchLabels:
      app: course-deployment
  template:
    metadata:
      labels:
        app: course-deployment
    spec:
      containers:
        - name: course-service
          image: asia-southeast1-docker.pkg.dev/programming-learning-system/backend-programming-learning-system-repository/course.service:1.0-SNAPSHOT
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://aws-postgresql.ctso2e4midpm.ap-southeast-2.rds.amazonaws.com:5432/course-service?currentSchema=public&binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "postgresadmin"
            - name: SPRING_DATASOURCE_INITIALIZATION-MODE
              value: "never"
            - name: KAFKA-CONFIG_BOOTSTRAP-SERVERS
              value: "gke-confluent-kafka-cp-kafka-headless:9092"
            - name: KAFKA-CONFIG_SCHEMA-REGISTRY-URL
              value: "http://gke-confluent-kafka-cp-schema-registry:8081"
          resources:
            limits:
              cpu: "500m"
              memory: "1024Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: course-service
  namespace: default
  labels:
    app: course-service
spec:
  selector:
    app: course-deployment
  ports:
    - name: course-service-port
      protocol: TCP
      port: 8184
  type: LoadBalancer
  loadBalancerIP: ""
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: course-deployment-hpa
  namespace: default
  labels:
    app: course-deployment
spec:
  scaleTargetRef:
    kind: Deployment
    name: course-deployment
    apiVersion: apps/v1
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 85
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-assessment-deployment
  labels:
    app: code-assessment-deployment
spec:
  selector:
    matchLabels:
      app: code-assessment-deployment
  template:
    metadata:
      labels:
        app: code-assessment-deployment
    spec:
      containers:
        - name: code-assessment-service
          image: asia-southeast1-docker.pkg.dev/programming-learning-system/backend-programming-learning-system-repository/code.assessment.service:1.0-SNAPSHOT
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://aws-postgresql.ctso2e4midpm.ap-southeast-2.rds.amazonaws.com:5432/code-assessment-service?currentSchema=customer&binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "postgresadmin"
            - name: SPRING_DATASOURCE_INITIALIZATION-MODE
              value: "never"
            - name: KAFKA-CONFIG_BOOTSTRAP-SERVERS
              value: "gke-confluent-kafka-cp-kafka-headless:9092"
            - name: KAFKA-CONFIG_SCHEMA-REGISTRY-URL
              value: "http://gke-confluent-kafka-cp-schema-registry:8081"
          resources:
            limits:
              cpu: "500m"
              memory: "1024Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: code-assessment-service
  namespace: default
  labels:
    app: code-assessment-service
spec:
  selector:
    app: code-assessment-deployment
  ports:
    - name: code-assessment-service-port
      protocol: TCP
      port: 8183
  type: LoadBalancer
  loadBalancerIP: ""
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: code-assessment-deployment-hpa
  namespace: default
  labels:
    app: code-assessment-deployment
spec:
  scaleTargetRef:
    kind: Deployment
    name: code-assessment-deployment
    apiVersion: apps/v1
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 85