{{- define "common.deployment" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deploymentName }}
  labels:
    app: {{ .Values.appLabel }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appLabel }}
  template:
    metadata:
      labels:
        app: {{ .Values.appLabel }}
    spec:
      containers:
      - name: {{ .Values.appLabel }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.containerPort }}
          protocol: TCP
        env:
        - name: LOGGING_LEVEL_COM_BACKEND_PROGRAMMING_LEARNING_SYSTEM
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.global.configMapName }}
              key: LOGGING_LEVEL_COM_BACKEND_PROGRAMMING_LEARNING_SYSTEM
        - name: LOGGING_LEVEL_ROOT
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.global.configMapName }}
              key: LOGGING_LEVEL_ROOT
        {{- if .Values.appname_enabled }}
        - name: SPRING_APPLICATION_NAME
          value: {{ .Values.appName }}
        {{- end }}
        {{- if .Values.eureka_instance_hostname_enabled }}
        - name: EUREKA_INSTANCE_HOSTNAME
          value: {{ .Values.eurekaInstanceHostname }}
        {{- end }}
        {{- if .Values.profile_enabled }}
        - name: SPRING_PROFILES_ACTIVE
          valueFrom: 
            configMapKeyRef:
              name: {{ .Values.global.configMapName }}
              key: SPRING_PROFILES_ACTIVE
        {{- end }}
        {{- if .Values.config_enabled }}
        - name: CONFIG_SERVER
          valueFrom: 
            configMapKeyRef:
              name: {{ .Values.global.configMapName }}
              key: CONFIG_SERVER
        {{- end }}
        {{- if .Values.discovery_enabled }}
        - name: EUREKA_SERVER
          valueFrom: 
            configMapKeyRef:
              name: {{ .Values.global.configMapName }}
              key: EUREKA_SERVER
        {{- end }}
        {{- if .Values.resouceserver_enabled }}
        - name: KEYCLOAK_DOMAIN
          valueFrom: 
            configMapKeyRef:
              name: {{ .Values.global.configMapName }}
              key: KEYCLOAK_DOMAIN
        {{- end }}
        {{- if .Values.otel_enabled }}
        - name: JAVA_TOOL_OPTIONS
          valueFrom: 
            configMapKeyRef:
              name: {{ .Values.global.configMapName }}
              key: JAVA_TOOL_OPTIONS
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          valueFrom: 
            configMapKeyRef:
              name: {{ .Values.global.configMapName }}
              key: OTEL_EXPORTER_OTLP_ENDPOINT
        - name: OTEL_METRICS_EXPORTER
          valueFrom: 
            configMapKeyRef:
              name: {{ .Values.global.configMapName }}
              key: OTEL_METRICS_EXPORTER
        - name: OTEL_SERVICE_NAME
          value: {{ .Values.appName }}
        {{- end }}
        {{- if .Values.kafka_enabled }}
        - name: KAFKA-CONFIG_BOOTSTRAP-SERVERS
          valueFrom: 
            configMapKeyRef:
              name: {{ .Values.global.configMapName }}
              key: KAFKA-CONFIG_BOOTSTRAP-SERVERS
        - name: KAFKA-CONFIG_SCHEMA-REGISTRY-URL
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.global.configMapName }}
              key: KAFKA-CONFIG_SCHEMA-REGISTRY-URL
        {{- end }}
        {{- if .Values.database_enabled }}
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://{{ .Values.global.springDatasourceHost }}:{{ .Values.global.springDatasourcePort }}/{{ .Values.springDatasourceDatabase }}?currentSchema=public&binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified"
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.global.configMapName }}
              key: SPRING_DATASOURCE_USERNAME
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.global.configMapName }}
              key: SPRING_DATASOURCE_PASSWORD
        - name: SPRING_DATASOURCE_INITIALIZATION-MODE
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.global.configMapName }}
              key: SPRING_DATASOURCE_INITIALIZATION-MODE
        {{- end }}
        {{- if .Values.redis_enabled }}
        - name: SPRING_DATA_REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.global.configMapName }}
              key: SPRING_DATA_REDIS_HOST
        - name: SPRING_DATA_REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.global.configMapName }}
              key: SPRING_DATA_REDIS_PORT
        {{- end }}
        {{- if .Values.resources_enabled }}
        resources:
          limits:
              cpu: "{{ .Values.resources.limits.cpu }}"
              memory: "{{ .Values.resources.limits.memory }}"
          requests:
              cpu: "{{ .Values.resources.requests.cpu }}"
              memory: "{{ .Values.resources.requests.memory }}"
        {{- end }}

{{- end -}}